### PR TITLE
Remove bundled ert

### PR DESCRIPTION
**Pull request by tarsius**
Ert was added to GNU Emacs in version 24.1, which was released in
2012.  Bundling a built-in or third-part library should generally
be avoided because the bundled version might end up being loaded
for users who also have a more recent version installed.

### CODE REVIEW

**Comment by echosa** [comment]
I don't maintain this project anymore, but thanks for the PR! I'll go ahead and merge it!

**Comment by tarsius** [comment]
Thanks! Does anyone still maintain it? Or should this maybe removed from Melpa?

**Comment by echosa** [comment]
As far as I know, it is unmaintained. Removing from Melpa might be a good idea.

**Comment by tarsius** [comment]
It has been downloaded close to five thousand times from Melpa. So maybe not.

/cc @purcell

**Comment by tarsius** [comment]
This package also contains some libraries that conflict with packages by the same name: `php-completion`, `php-doc`, `string-utils`. Would you accept a pr to change the prefix to `php+-`?

**Comment by echosa** [comment]
@tarsius Absolutely! Send in any PRs for changes you think are relevant! As I said, I no longer maintain this, but if someone else wants to do the work for me, I certainly won't say no! :-)

**Comment by tarsius** [comment]
I have renamed the libraries and adjusted the `provide` and `require` forms accordingly. Not that this won't prevent all conflicts. Since the symbols still use the `php-` prefix, some of them might very well conflict with libraries from other packages. However this also applies to other libraries that did already not conflict based on the *library name* before this commit, so I consider that a separate issue and think this change is a step in the right direction. (Though since you are no longer maintaining this, maybe the last step ;-)

**Comment by echosa** [comment]
Excellent! I assume you'll make a new PR for me to merge when ready? Or are you just going to maintain your own fork. I'm fine either way. :-)

**Comment by tarsius** [comment]
I didn't realize I had to create a new pr (because you already merged this one).

**Pull request merged**
